# Development Docker Compose Override
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  backend:
    environment:
      ENVIRONMENT: development
    volumes:
      - ../Backend:/app
      - /app/__pycache__
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ../Frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
